### ISSUE TITLE
希望更新

### ISSUE THREAD

**Issue by yggcwx** [bilibili-koryking/1panel-docker#3]
非常好的项目，感谢您的无私奉献！
希望您能抽空更新一下，绿联现在已经可以直接部署docker-compose文件了呢。

**Comment by dylan-tao** [comment]
拿去吧，这个会默认拉取官方最稳定版本，当前是32版本，也就是当触发容器安装1panel时决定安装时拉取官方的稳定版本号，如果要升级最新稳定版本，则删除1panel当前的docker镜像会自动拉取最新稳定版本，并更新SQLite数据库。目前看此镜像无需再更新。
```
services:
  1panel:
    container_name: 1panel
    image: koryking/1panel:latest
    privileged: true
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes:/var/lib/docker/volumes
      - /volume4/docker/1panel/opt:/volume4/docker/1panel/opt
      - ./root:/root
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/volume4/docker/1panel/opt
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=xxx
      - PANEL_USERNAME=xxx
      - PANEL_PASSWORD=123
    labels:
      createdBy: "Apps"
```

**Comment by dylan-tao** [comment]
> 非常好的项目，感谢您的无私奉献！ 希望您能抽空更新一下，绿联现在已经可以直接部署docker-compose文件了呢。

拿去吧，这个会默认拉取官方最稳定版本，当前是32版本，也就是当触发容器安装1panel时决定安装时拉取官方的稳定版本号，如果要升级最新稳定版本，则删除1panel当前的docker镜像会自动拉取最新稳定版本，并更新SQLite数据库。目前看此镜像无需再更新。下面的/volume4/docker/1panel/opt路径你可以自定义，但三处必须保持一致。

```
services:
  1panel:
    container_name: 1panel
    image: koryking/1panel:latest
    privileged: true
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes:/var/lib/docker/volumes
      - /volume4/docker/1panel/opt:/volume4/docker/1panel/opt
      - ./root:/root
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/volume4/docker/1panel/opt
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=xxx
      - PANEL_USERNAME=xxx
      - PANEL_PASSWORD=123
    labels:
      createdBy: "Apps"
```
